sonar.projectKey=tasklist-backend
sonar.projectName=TaskList Backend
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.test.ts
sonar.exclusions=node_modules/**,dist/**,coverage/**,prisma/**

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info
